// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADMuPHuvFsAAkYizYAEXztbMY2M8N7NQI',
    appId: '1:682874596374:web:06077cf45f2a28e97e1937',
    messagingSenderId: '682874596374',
    projectId: 'spotwise-12f82',
    authDomain: 'spotwise-12f82.firebaseapp.com',
    storageBucket: 'spotwise-12f82.firebasestorage.app',
    measurementId: 'G-KZB1M3WHNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2zBi_aem9WJzdTvi0eMvov0HT-bwAKWI',
    appId: '1:682874596374:android:78ccaff88d8058317e1937',
    messagingSenderId: '682874596374',
    projectId: 'spotwise-12f82',
    storageBucket: 'spotwise-12f82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBASc4WEEo4M3iFSBKQbXeHt7dS5F1yji4',
    appId: '1:682874596374:ios:5a9d1b721c9889827e1937',
    messagingSenderId: '682874596374',
    projectId: 'spotwise-12f82',
    storageBucket: 'spotwise-12f82.firebasestorage.app',
    iosBundleId: 'com.example.spotwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBASc4WEEo4M3iFSBKQbXeHt7dS5F1yji4',
    appId: '1:682874596374:ios:5a9d1b721c9889827e1937',
    messagingSenderId: '682874596374',
    projectId: 'spotwise-12f82',
    storageBucket: 'spotwise-12f82.firebasestorage.app',
    iosBundleId: 'com.example.spotwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADMuPHuvFsAAkYizYAEXztbMY2M8N7NQI',
    appId: '1:682874596374:web:c26f51ab291af9ce7e1937',
    messagingSenderId: '682874596374',
    projectId: 'spotwise-12f82',
    authDomain: 'spotwise-12f82.firebaseapp.com',
    storageBucket: 'spotwise-12f82.firebasestorage.app',
    measurementId: 'G-L96QGJT4MT',
  );
}
